artifacts_root: artifacts

# dictionary format of yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformation  
  local_train_OD_dir: artifacts/data_transformation/OD/train
  local_val_OD_dir: artifacts/data_transformation/OD/validation
  local_test_OD_dir: artifacts/data_transformation/OD/test
  local_train_tensor_dir: artifacts/data_transformation/tensor/train
  local_val_tensor_dir: artifacts/data_transformation/tensor/validation
  local_test_tensor_dir: artifacts/data_transformation/tensor/test


