artifacts_root: artifacts

# dictionary format of yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformation  
  local_train_od_dir: artifacts/data_transformation/od/train.pkl  
  local_test_od_dir: artifacts/data_transformation/od/test.pkl
  local_scaler_od_dir: artifacts/data_transformation/od/scaler.pkl
  local_train_tensor_dir: artifacts/data_transformation/tensor/train.pkl 
  local_test_tensor_dir: artifacts/data_transformation/tensor/test.pkl
  local_scaler_tensor_dir: artifacts/data_transformation/tensor/scaler.pkl


prepare_autoencoder_base_model:
  root_dir: artifacts/prepare_autoencoder_base_model
  base_od_model_path: artifacts/prepare_autoencoder_base_model/base_od_model.h5 
  base_tensor_model_path: artifacts/prepare_autoencoder_base_model/base_tensor_model.h5 

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  ckeckpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training_autoencoder:
  root_dir: artifacts/training_autoencoder
  trained_od_model_path: artifacts/training_autoencoder/od_model.h5
  trained_tensor_model_path: artifacts/training_autoencoder/tensor_model.h5

prepare_timeseries_base_model:
  root_dir: artifacts/prepare_timeseries_base_model
  base_od_model_path: artifacts/prepare_timeseries_base_model/base_od_model.h5 
  base_tensor_model_path: artifacts/prepare_timeseries_base_model/base_tensor_model.h5 


training_timeseries:
  root_dir: artifacts/training_timeseries
  trained_od_model_path: artifacts/training_timeseries/od_model.h5
  trained_tensor_model_path: artifacts/training_timeseries/tensor_model.h5